<a href="https://colab.research.google.com/github/JeromeCheon/gcs_AIproject/blob/master/assignments/hw2_pandas_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1.

#In the cell below, create a DataFrame `fruits` that looks like this:

![](https://i.imgur.com/Ax3pp2A.png)

In [ ]:
import pandas as pd
#q1.solution()
fruits = pd.DataFrame({'Apple': {0:30},'Bananas':{0:21}})
fruits
# pd.Series({'Apple':30, 'Bananas':30})

Apple  Bananas
0     30       21

## 2.

Create a dataframe `fruit_sales` that matches the diagram below:

![](https://i.imgur.com/CHPn7ZF.png)

In [ ]:
# q2
#fruit_sales = ____
fruit_sales = pd.DataFrame({'Apple': {'2017 Sales':35, '2018 Sales':41},'Bananas':{'2017 Sales':21, '2018 Sales':34}})
fruit_sales

Apple  Bananas
2017 Sales     35       21
2018 Sales     41       34

## 3.
## Question : Create a 1D array of numbers from 0 to 9
## Output :  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])



In [ ]:
import numpy as np
#q3
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 4.
## Question: Convert a 1D array to a 2D array with 2 rows
## input: np.arange(10)
## output array([[0, 1, 2, 3, 4],
##               [5, 6, 7, 8, 9]])


In [ ]:
#q4
np.arange(10).reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 5.
## Question: From the array a, replace all values greater than 30 to 30 and less than 10 to 10.


In [ ]:
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50,20)
#q5
a[a>30] = 30
a[a<10] = 10
a

array([27.63, 14.64, 21.8 , 30.  , 10.  , 10.  , 30.  , 30.  , 10.  ,
       29.18, 30.  , 11.25, 10.08, 10.  , 11.77, 30.  , 30.  , 10.  ,
       30.  , 14.43])