# Pytorch

# Pytorch Packages

 - **torch**
 - torch.autograd
 - torch.nn
 - torch.optim
 - torch.multiprocessing
 - torch.utils

# Pytorch Tensor Basic Usage

- Create Tensor
- Indexing, Joining, Slicing
- Initialization
- Math Operations

## 1. Create Tensor

### 1) random numbers

In [1]:
from __future__ import print_function
import torch

In [2]:
# torch.rand(size)
# 0~1 사이의 연속균등분포에서 값을 뽑아 5x3 텐서를 생성합니다. ~U(0,1)
x = torch.rand(2,3)
x

tensor([[0.9629, 0.6577, 0.9516],
        [0.3372, 0.0503, 0.9426]])

In [3]:
# torch.randn(size)
# randn의 경우 평균은 0, 표준편차는 1인 정규분포에서 값을 가져옵니다. ~z(0,1)
x = torch.randn(2,3)
x

tensor([[ 1.9806, -0.9301,  0.8238],
        [ 0.5261,  0.6744,  1.0010]])

In [4]:
# torch.randperm(n)
# 0부터 n-1까지 1씩 늘어나며 값을 랜덤으로 정렬합니다.
x = torch.randperm(5)
x

tensor([1, 4, 2, 0, 3])

### 2) empty, zeros, ones, arange, max

In [5]:
# torch.empty(size)
# 원하는 크기의 아주 작은 값을 가진 텐서를 생성합니다. dtype은 input에 따라 결정됩니다.
x = torch.empty(2,3)
x[0]

tensor([3.4839e+28, 3.0966e-41, 3.3631e-44])

In [6]:
x.size()

torch.Size([2, 3])

In [7]:
# torch.zeros(size)
# 원하는 크기의 0 값을 가진 텐서를 생성합니다.
x = torch.zeros(2,3)
x[0]

tensor([0., 0., 0.])

In [8]:
# torch.ones(size)
# 원하는 크기의 1의 값을 가진 텐서를 생성합니다.
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# torch.arange(start,end,step=1)
# start값부터 end값 전까지 step만큼 더하며 텐서를 생성합니다.
x = torch.arange(0,3,step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

In [10]:
x.size()

torch.Size([6])

In [11]:
# torch.max(input, dim, keepdim=False, out=None) -> (Tensor, LongTensor)
# tensor의 최대값을 산출합니다.

x = torch.rand(2,3)
print(x)

tensor([[0.6989, 0.6921, 0.0271],
        [0.4069, 0.0194, 0.4914]])


In [12]:
# 최대값을 출력합니다.
print(torch.max(x))

tensor(0.6989)


In [26]:
# 해당 차원에서 최대값과 그 위치를 출력합니다.
print(torch.max(x,0))

torch.return_types.max(
values=tensor([1.0325, 0.3451, 3.3639]),
indices=tensor([0, 2, 1]))


In [24]:
print(torch.max(x, 0).values.shape)

torch.Size([3])


In [14]:
print(torch.max(x,0)[1])
print(x.size(), torch.max(x,0)[1].size())

tensor([0, 0, 1])
torch.Size([2, 3]) torch.Size([3])


In [15]:
# 위치를 출력합니다.
print(torch.max(x,1)[1])
print(x.size(), torch.max(x,1)[1].size())

tensor([0, 2])
torch.Size([2, 3]) torch.Size([2])


### 3) Tensor Data Type

| Data type               | dtype                                         | Tensor types                 |
|:-------------------------|:-----------------------------------------------|:------------------------------|
| 32-bit floating point   | ``` torch.float32 ``` or ``` torch.float ```  | ``` torch.*.FloatTensor ```  |
| 64-bit floating point   | ``` torch.float64 ``` or ``` torch.double ``` | ``` torch.*.DoubleTensor ``` |
| 16-bit floating point   | ``` torch.float16 ``` or ``` torch.half ```   | ``` torch.*.HalfTensor ```   |
| 16-bit integer (signed) | ``` torch.int16 ``` or ``` torch.short ```    | ``` torch.*.ShortTensor ```  |
| 32-bit integer (signed) | ``` torch.int32 ``` or ``` torch.int ```      | ``` torch.*.IntTensor ```    |
| 64-bit integer (signed) | ``` torch.int64 ``` or ``` torch.long ```     | ``` torch.*.LongTensor ```   |

In [16]:
# torch.empty(size, dtype=)
# torch.zeros(size, dtype=)
# torch.arange(start,end,dtype=)

# torch에서 지원하는 다양한 data type을 옵션으로 지정할 수 있습니다.

x = torch.empty(2,3, dtype=torch.float)
y = torch.zeros(2,3, dtype = torch.long)
z = torch.arange(0,3,step=0.5,dtype=torch.double)

print(x)
print(y)
print(z)

tensor([[3.4840e+28, 3.0966e-41, 7.1990e+24],
        [3.0966e-41, 3.2230e-44, 0.0000e+00]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000], dtype=torch.float64)


In [17]:
# torch.tensor(size or list, dtype = torch.floattensor) 
# 원하는 텐서를 바로 생성합니다.
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [18]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2,3)
print(x)
x = torch.FloatTensor([2,3])
print(x)

tensor([[3.4841e+28, 3.0966e-41, 3.7835e-44],
        [0.0000e+00,        nan, 1.9375e+00]])
tensor([2., 3.])


In [19]:
# tensor.type_as(tensor_type)
# tensor 형 변환
x = x.type_as(torch.IntTensor())
x

tensor([2, 3], dtype=torch.int32)

### 4) Tensor Size

In [27]:
# tensor.size()

x = torch.FloatTensor(10,12,3,3)

print(x.size()[:])
print(x.size()[0])

torch.Size([10, 12, 3, 3])
10


In [29]:
x = x.new_ones(5,3, dtype=torch.double) #5,3 차원의 새로운 텐서를 생성합니다.
print(x)

x = torch.randn_like(x,dtype=torch.float) # 같은 size에서 랜덤한 숫자로 채워진 텐서를 생성합니다.
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.2886, -1.9133,  2.7732],
        [-0.4944, -0.4170,  1.0939],
        [-0.8291, -0.5580, -1.5951],
        [-2.8714,  0.4912,  0.2980],
        [-1.7624,  0.2294, -0.3070]])


In [30]:
y = torch.randn_like(x, dtype=torch.float)
print(y)

tensor([[-0.0080,  0.6689, -0.3814],
        [-0.2841, -1.9196, -0.1028],
        [ 1.0469, -0.4606,  0.0523],
        [ 1.4945, -0.6984, -0.1865],
        [ 0.1046, -1.1631,  0.6586]])


## 2. Math Operations

### 1) add, mul, div

In [31]:
# torch.add()
# 텐서의 값끼리 더합니다.

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1, x2)

x1,x2,add,x1+x2,x1-x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [32]:
#차원이 다르더라도 안쪽 차원만 같으면 연산이 가능합니다.

x = torch.rand(1,5,3)
y = torch.rand(5,3)
x, y, torch.add(x,y)

(tensor([[[0.8392, 0.9776, 0.4064],
          [0.6682, 0.9204, 0.3231],
          [0.1818, 0.9919, 0.6610],
          [0.6590, 0.5642, 0.1190],
          [0.6417, 0.3754, 0.3147]]]), tensor([[0.7304, 0.0864, 0.5552],
         [0.3899, 0.2051, 0.6578],
         [0.5758, 0.2886, 0.2122],
         [0.0943, 0.3316, 0.7877],
         [0.1884, 0.2939, 0.3514]]), tensor([[[1.5697, 1.0641, 0.9616],
          [1.0580, 1.1255, 0.9809],
          [0.7576, 1.2805, 0.8732],
          [0.7533, 0.8957, 0.9068],
          [0.8301, 0.6693, 0.6661]]]))

In [33]:
# torch.add 말고 add_의 경우에는 이러한 연산 기능이 지원되지 않습니다. 따라서 먼저 x를 같은 차원으로 바꿔줍니다.

x = torch.rand(5,3)
y.add_(x)
print(y)

tensor([[0.8310, 0.5459, 1.3148],
        [0.6371, 0.7359, 1.2510],
        [0.5810, 0.8241, 1.0105],
        [0.8701, 1.2465, 1.7216],
        [0.4559, 1.2575, 0.5101]])


In [34]:
# x 텐서의 2열을 불러옵니다. numpy 연산이 지원됩니다.

print(x)
print(x.shape)
print(x[:,1])
print(x[:,1].shape)

tensor([[0.1006, 0.4595, 0.7595],
        [0.2472, 0.5308, 0.5933],
        [0.0052, 0.5354, 0.7983],
        [0.7758, 0.9149, 0.9338],
        [0.2675, 0.9637, 0.1587]])
torch.Size([5, 3])
tensor([0.4595, 0.5308, 0.5354, 0.9149, 0.9637])
torch.Size([5])


In [35]:
# torch.mul()
# hadamard product, mxn, mxn 행렬 2개를 곱합니다. 덧셈에 대해 분배법칙을 따릅니다.

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.mul(x1,x2)

x1.size(), x2.size(), x3.size(), x1, x2, x3

(torch.Size([2, 3]),
 torch.Size([2, 3]),
 torch.Size([2, 3]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]))

In [36]:
# torch.mul()

x1 = torch.FloatTensor([[1,2,3,],[4,5,6]])
x2 = x1*10

x2

tensor([[10., 20., 30.],
        [40., 50., 60.]])

In [37]:
# torch.div()

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.div(x1,x2)

x3

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [38]:
# torch.div()

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])

x1/5

tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])

### 2) pow, exp, log

In [39]:
# torch.pow(input,exponent)

x1 = torch.rand(3,4)

print(x1)
print(torch.pow(x1,2),"\n",x1**2)

tensor([[0.5213, 0.2100, 0.6503, 0.0953],
        [0.0596, 0.0573, 0.1457, 0.0563],
        [0.3034, 0.8380, 0.0460, 0.3454]])
tensor([[0.2718, 0.0441, 0.4228, 0.0091],
        [0.0036, 0.0033, 0.0212, 0.0032],
        [0.0920, 0.7022, 0.0021, 0.1193]]) 
 tensor([[0.2718, 0.0441, 0.4228, 0.0091],
        [0.0036, 0.0033, 0.0212, 0.0032],
        [0.0920, 0.7022, 0.0021, 0.1193]])


In [40]:
# torch.exp(tensor,out=None)

x1 = torch.rand(3,4)

print(x1)
print(torch.exp(x1))

tensor([[0.8250, 0.9294, 0.4137, 0.4493],
        [0.0165, 0.6050, 0.6953, 0.6565],
        [0.2529, 0.3576, 0.3179, 0.1220]])
tensor([[2.2819, 2.5329, 1.5124, 1.5672],
        [1.0166, 1.8313, 2.0043, 1.9280],
        [1.2877, 1.4299, 1.3743, 1.1297]])


In [41]:
# torch.log(input,out=None)

x1 = torch.rand(3,4)

print(x1)
print(torch.log(x1))

tensor([[0.5840, 0.3539, 0.1617, 0.4945],
        [0.6757, 0.3539, 0.5941, 0.5618],
        [0.8324, 0.8696, 0.2187, 0.7190]])
tensor([[-0.5378, -1.0388, -1.8219, -0.7043],
        [-0.3920, -1.0386, -0.5206, -0.5767],
        [-0.1834, -0.1398, -1.5199, -0.3299]])


In [42]:
# torch.mm(matrix1, matrix2)

x1 = torch.rand(3,4)
x2 = torch.rand(4,5)

torch.mm(x1,x2)

tensor([[1.7647, 0.8764, 0.9232, 1.2133, 1.1562],
        [2.3452, 1.3747, 1.0703, 1.0651, 1.2637],
        [1.9100, 0.9020, 0.9789, 1.3322, 1.2199]])

In [44]:
# torch.bmm(batch_matrix1, batch_matrix2)

x1 = torch.rand(10,3,4)
x2 = torch.rand(10,4,5)

torch.bmm(x1,x2) #.size()

tensor([[[0.5877, 1.7023, 1.0118, 1.1061, 1.4521],
         [0.6196, 0.9983, 0.5613, 0.6542, 0.6107],
         [1.1401, 1.6422, 0.8279, 1.3868, 1.1359]],

        [[1.1758, 0.7845, 1.1640, 0.7056, 1.0075],
         [1.7036, 0.9417, 1.0917, 0.7366, 1.1637],
         [1.1272, 0.9196, 1.1624, 0.7723, 1.0692]],

        [[1.0087, 1.0127, 0.6056, 1.4826, 0.8809],
         [0.8493, 0.6201, 0.5417, 0.9679, 0.7292],
         [1.0311, 0.5297, 0.6071, 0.9293, 0.7824]],

        [[0.6957, 0.6101, 0.1363, 0.3598, 0.6733],
         [1.2915, 1.3163, 0.1860, 0.8622, 1.4764],
         [0.8569, 0.9067, 0.2326, 0.1886, 0.6058]],

        [[0.9895, 0.9459, 0.2026, 1.0693, 0.7441],
         [1.2693, 1.0448, 0.3099, 1.0431, 0.7877],
         [1.2804, 1.0249, 0.3718, 0.6237, 0.6102]],

        [[1.5690, 1.1696, 1.0180, 1.5707, 1.1322],
         [0.8776, 0.7752, 0.6030, 0.8614, 0.6211],
         [1.4224, 0.5796, 1.2953, 0.9461, 1.2066]],

        [[1.7199, 1.1778, 1.6419, 1.4172, 2.1410],
         [1.3276, 0

![img](https://github.com/shwksl101/Pytorch-A-to-Z/blob/master/img/innerproduct.PNG?raw=true)

In [45]:
# torch.dot(tensor1, tensor2)

torch.dot(torch.tensor([2,3]), torch.tensor([2,1]))

tensor(7)

In [46]:
# torch.t(matrix)
# tranpose

x1 = torch.rand(3,4)
print(x1.size(), x1.t().size())

torch.Size([3, 4]) torch.Size([4, 3])


In [47]:
# torch.transpose(input,dim0,dim1)

x1 = torch.rand(10,3,4)
x1.size(), torch.transpose(x1,1,2).size(), x1.transpose(1,2).size() #contiguous

(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [48]:
# torch.eig(a,eigenvectors=Flase)
# eigen_value, eigen_vector

x1 = torch.rand(2,2)

print(x1,"\n",torch.eig(x1,True)

SyntaxError: ignored

### 3) view, item

In [49]:
# view()

x = torch.randn(4,4)
y = x.view(16)
# -1은 나머지
z = x.view(-1,8) # -1의 경우 다른 차원들로 유추합니다. 이 경우에는 2로 유추합니다.
print(x.size())
print(y.size(),y)
print(z.size(),z)

torch.Size([4, 4])
torch.Size([16]) tensor([-0.1111, -0.7352,  0.6114,  0.1637,  0.1044, -1.1038,  0.8522, -0.8792,
         1.8940,  0.5406, -0.1192, -0.6366, -0.0095, -2.2817,  0.0426, -1.3755])
torch.Size([2, 8]) tensor([[-0.1111, -0.7352,  0.6114,  0.1637,  0.1044, -1.1038,  0.8522, -0.8792],
        [ 1.8940,  0.5406, -0.1192, -0.6366, -0.0095, -2.2817,  0.0426, -1.3755]])


In [50]:
# item()

x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0348])
1.0348130464553833


- 더 많은 연산은 다음의 링크에서 참고하세요 https://pytorch.org/docs/stable/torch.html

## 3. Tensor to Numpy, Numpy to Tensor

In [51]:
import numpy as np

In [52]:
a = torch.ones(5) # 1로 채워진 텐서를 생성합니다.
print(a)

tensor([1., 1., 1., 1., 1.])


In [53]:
# tensor.numpy()

b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [54]:
# torch.from_numpy(ndarray)

a = np.ones(5) #a와 b는 연동됩니다.
b = torch.from_numpy(a)

np.add(a,1,out=a)

print(a)
print(b) #chartensor를 제외한 모든 tensor는 numpy로의 변환을 지원합니다.

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## 4. Tensor on GPU

In [55]:
x= torch.FloatTensor([[1,2,3],[4,5,6]])

if torch.cuda.is_available():
    x_cuda = x.cuda()
else:
    x_cuda = x.cpu()
    
print(x_cuda)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [62]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu")) #.to 기능을 tensor를 GPU로 연산할 수 있습니다
    print(z.to("cuda"))

In [64]:
# cuda 사용이 가능하면 아래 연산은 gpu 자원을 사용해서 해결하겠다 하는 것 
# a = torch.randn(3, device=torch.device('cuda'))
# b = torch.randn(3).cuda()
# c = a + b

## 5. Indexing, Slicing, Joining

### 1) Indexing

In [57]:
# tensor.index_select(input,dim,index)

x = torch.rand(4,3)
out = torch.index_select(x,0,torch.LongTensor([0,3]))
# index는 꼭 Longtensor로 입력해야 합니다.

print(x.size(), out.size())
print(x, "\n", out)

torch.Size([4, 3]) torch.Size([2, 3])
tensor([[0.6862, 0.1188, 0.4020],
        [0.2579, 0.1952, 0.7264],
        [0.8753, 0.7649, 0.6421],
        [0.3006, 0.6476, 0.0405]]) 
 tensor([[0.6862, 0.1188, 0.4020],
        [0.3006, 0.6476, 0.0405]])


In [58]:
print(x.size(),'\n', x)
print(x[:,0].size(),x[:,0])
print(x[0,:].size(),x[0,:])
print(x[0:2,0:2].size(),'\n', x[0:2,0:2])

torch.Size([4, 3]) 
 tensor([[0.6862, 0.1188, 0.4020],
        [0.2579, 0.1952, 0.7264],
        [0.8753, 0.7649, 0.6421],
        [0.3006, 0.6476, 0.0405]])
torch.Size([4]) tensor([0.6862, 0.2579, 0.8753, 0.3006])
torch.Size([3]) tensor([0.6862, 0.1188, 0.4020])
torch.Size([2, 2]) 
 tensor([[0.6862, 0.1188],
        [0.2579, 0.1952]])


### 2) Joining

In [59]:
# torch.cat(seq, dim=0)
# dim을 기준으로 tensor를 합칩니다.
# dim = 0은 행, dim = 1은 열 기준입니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0)
z2 = torch.cat([x,y],dim = 1)

print(x)
print(y)
print(z1)
print(z2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]])


In [65]:
# torch.stack(sequence,dim=0)
# dim을 기준으로 쌓습니다.

x = torch.FloatTensor([1,2,3])
x_stack = torch.stack([x,x],dim=0)
x_stack2 = torch.stack([x,x],dim=1)

print(x_stack,"\n",x_stack2)

tensor([[1., 2., 3.],
        [1., 2., 3.]]) 
 tensor([[1., 1.],
        [2., 2.],
        [3., 3.]])


### 3) Slicing

In [66]:
# torch.chunk(tensor, chunks, dim=0)
# tensor를 chunk 단위로 쪼갭니다. chunk 개수 만큼 생성합니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0)

# 동일한 사이즈로 자르는 함수이다
x_1, x_2 = torch.chunk(z1,2,dim=0)
y_1, y_2, y_3 = torch.chunk(z1,3,dim=1)

print(z1)
print(x_1)
print(x_2)
print(y_1)
print(y_2)
print(y_3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.],
        [ 4.],
        [ 7.],
        [10.]])
tensor([[ 2.],
        [ 5.],
        [ 8.],
        [11.]])
tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]])


In [67]:
# torch.split(tensor,split_size,dim=0) 각 size가 split_size만큼인 것을 생성합니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0)

x1,x2 = torch.split(z1,2,dim=0)
y1,y2 = torch.split(z1,2,dim=1)

print(z1)
print(x1)
print(x2)
print(y1)
print(y2)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])
tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]])


### 4) squeezing

In [68]:
# torch.squeeze(input, dim=None)
# 1짜리 차원을 줄입니다.

x1 = torch.FloatTensor(10,1,3,1,4)
x2 = torch.squeeze(x1)

x1.size(), x2.size()

(torch.Size([10, 1, 3, 1, 4]), torch.Size([10, 3, 4]))

In [69]:
# torch.unsqueeze(input,dim=None)
# 1짜리 차원을 더합니다.

x1 = torch.FloatTensor(10,3,4)
x2 = torch.unsqueeze(x1,dim=0)

x.size(), x2.size()

(torch.Size([2, 3]), torch.Size([1, 10, 3, 4]))

## 6. Initialization

In [70]:
import torch.nn.init as init

x1 = init.uniform_(torch.FloatTensor(3,4),a=0,b=9) 
x2 = init.normal_(torch.FloatTensor(3,4),std=0.2)
x3 = init.constant_(torch.FloatTensor(3,4),3.1415)

x1,x2,x3

(tensor([[1.1029, 7.5003, 7.8914, 4.5186],
         [4.9061, 8.0658, 0.8865, 7.3221],
         [1.1308, 2.4205, 5.9126, 3.4688]]),
 tensor([[-0.1468, -0.2421,  0.1406, -0.1289],
         [ 0.0665,  0.0538, -0.4931, -0.2037],
         [-0.1422, -0.0704,  0.0289,  0.0061]]),
 tensor([[3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415]]))